### ISSUE TITLE
weex run ios

### ISSUE THREAD

**Issue by JLraining** [charlesace/weex-app#1]
- (void)request:(WXResourceRequest *)request didFinishCollectingMetrics:(NSURLSessionTaskMetrics *)metrics API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0));

这段没问题的么 可以跑么

**Comment by charlesace** [comment]
可以跑，如果不能跑可能是你系统和XCode版本过老的问题

**Comment by charlesace** [comment]
@JLraining 可以跑，如果不能跑可能是你系统和XCode版本过低的问题
